# Generated by Django 4.1 on 2023-11-05 00:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jpstores', '0002_productimage_image_alter_productimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
