# Generated by Django 4.1 on 2023-11-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jpstores', '0004_alter_user_card_number_alter_user_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='thumbnail_url',
            new_name='thumbnail',
        ),
    ]
